### ISSUE TITLE
Bulgarian Cyrillic

### ISSUE THREAD

**Issue by StefanPeev** [sharanda/manrope#1]
There are some issues concerning Bulgarian Cyrillic in Manrope.
1. It's needed uni045D to be substituted with a uni045D.loclBGR (ѝ) when custumer switch to Bulgarian language.
2. The design of all loclBGR glyphs is just the same as for the international Cyrillic glyphs. It means that actually there are not local forms for Bulgarian Cyrillic.
3. It's a good idea SS01 to be included as an opption for switching between international Cyrillic and Bulgarian Cyrillic.
4. It's a good idea also to upload UFO masters of the Manrope.

**Comment by sharanda** [comment]
Thanks for your feedback, Stefan!

1,2,3. Noted. I will look closer into it in a few days. I’m afraid, Bulgarian Cyrillics were automatically generated.

4. I can do that. Will provide with next update.

**Comment by StefanPeev** [comment]
Look [here](https://localfonts.eu/typography-basics/fonts-the-importance-of-localisation/local-features/cyrillic-local-forms/), Michael – I hope this place will be of help for you.

**Comment by sharanda** [comment]
@StefanPeev Thanks! I tried to learn it and I followed article from your reference. Just provided an update.

1. Could you elaborate why exactly? I couldn't find a difference between uni045D "iigrave-cy" and local Bulgarian version...
2. Fixed. (might need to do some more tests)
3. Do you mean to make Bulgarian Cyrillic characters as alternatives to international Cyrillic?
4. Sorry, I'm afraid I can't provide it. I tried, but Glyphes app doesn't seem to export to UFO format correctly...

Thank you for your help!

**Comment by StefanPeev** [comment]
1. Because uni045D "iigrave-cy" (ѝ) is needed mainly for Bulgarian language (it is not used in Russian, Serbian or any other Cyrillic language). And if you include local Bulgarian feature in your font, you need to make substitution between uni0438 + grave = uni045D and uni0438.loclBGR + grave = uni045D.loclBGR.

![bulgarian_uni045d loclbgr](https://user-images.githubusercontent.com/12949369/42536772-a77bbb8a-849b-11e8-979c-72c299300a1c.jpg)

3. It is enough to add this:

feature ss01 {
 script cyrl;
 language BGR  exclude_dflt;
    sub @locl1 by @locl2;
} ss01;

**Comment by sharanda** [comment]
@StefanPeev thanks! I just pushed an update. Could you please check if I made it correctly?

**Comment by StefanPeev** [comment]
Well, now there is uni045D.loclBGR in your fonts (I've checked only Regular of OTF and TTF), but in **class locl2** you have substituted **uni045D** (ѝ) with **uni0439** – the substitution must be between **uni045D** and **uni045D.loclBGR**. In Bulgarian language there is a great difference between uni0439 (й) and uni045D (resp. in its local Bulgarian form – uni045D.loclBGR). The word 'her' (in its short form) Bulgarian people write with uni045D (resp. uni045D.loclBGR). The glyph uni0439 (й) never means a word.

**Comment by StefanPeev** [comment]
Here is a ZIP archiv with Manrope-Regular.otf, Manrope-Regular.ttf and features.fea files. I've changed the classes and everything else in the feature.fea file (and in the OTF and TTF files also). You could see in all of them what I've have in mind.

[Manrope-Regular.zip](https://github.com/sharanda/manrope/files/2193537/Manrope-Regular.zip)

**Comment by StefanPeev** [comment]
Now is OK. Thanks!
