### ISSUE TITLE
Accents issue in castilian

### ISSUE THREAD

**Issue by davetapiamartin** [sharanda/manrope#10]
Hi!
Something strange happens when you type some character with spanish regular accent ("á" for example), at least in Adobe Illustratror and Photoshop. Automatically the type change to another default type and if you continue typing, all the text in advance changes. You need to select the character with accent and change manually. 
There's something wrong with it?

Thanx in advance!

**Comment by davetapiamartin** [comment]
![captura de pantalla 2019-01-30 a las 20 04 14](https://user-images.githubusercontent.com/47191152/52005562-48823f80-24ca-11e9-96a7-67579b4b7953.png)

**Comment by sharanda** [comment]
@davetapiamartin hi, sorry for late response. I couldn't replicate your issue. What kind of OS and typing software you are using? I released a new version recently, can you check if the issue still exists?

**Comment by jhewt** [comment]
Hi, this also happens on web using the latest release from this repository. I'm on OSX 10.12 and happens on both Chrome and Firefox regardless their versions.

![Captura de pantalla 2019-04-14 a la(s) 05 38 32](https://user-images.githubusercontent.com/3622160/56090383-169d3a00-5e78-11e9-93b7-893563eac742.png)

**Comment by sharanda** [comment]
@jhewt @davetapiamartin the issue should be fixed now. Thanks for reporting and sorry about that.

**Comment by jhewt** [comment]
Thanks for taking care of it. Great work, awesome font!

**Comment by davetapiamartin** [comment]
Thank you so much!!
