### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by EuriNaiz** [sharanda/manrope#104]
Just that, the website seems to be offline

**Comment by sharanda** [comment]
@EuriNaiz pls go to https://gent.media/manrope :-)

**Comment by EuriNaiz** [comment]
Merci beaucoup c:

**Comment by sawyerh** [comment]
@sharanda heads up, the GitHub repo still links to the old broken URL: 
![CleanShot 2023-10-15 at 17 30 04@2x](https://github.com/sharanda/manrope/assets/371943/10787332-ee34-4052-aa5f-28ee1d026806)
