### ISSUE TITLE
wrong abostrophe in german language

### ISSUE THREAD

**Issue by am-cmyk** [sharanda/manrope#15]
Love your Font. Absolute clean with own character.
Found out that the abostrophe for the german language shows in the wrong direction.
It starts with a "99" on the bottom and correctly ends with a "66" on the top. Manrope ends with a mirrored "99" and there is no "66" glyph.
Would be nice if you could correct it.
Thanks and best wishes

**Comment by sharanda** [comment]
@am-cmyk thank you for your feedback. Yeah, there’s an appropriate Unicode character U+201F for the reversed one. Will fix

**Comment by bghryct** [comment]
@sharanda did you end up fixing this?

**Comment by sharanda** [comment]
@bghryct yes, it has been fixed in v4 branch. *forgot to mention
