### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by dtzWill** [sharanda/manrope#18]
Thanks for the font, and for making it available!!

Tagging the releases makes it clear which revision is "v3" or "v4", and makes this font more friendly to downstream packagers as many distributions have policies regarding preferring tags and official releases.

On a related subject, is the merging of #17 indicative of "V4" being released or is that still WIP (since the PR was sent to a branch?).

**Comment by sharanda** [comment]
@dtzWill thanks for pointing out. My understanding was that it's WIP, until it's merged with the master branch

**Comment by 0mp** [comment]
Tagging would also allowed automated tools to detect when a new version is available. I've [packaged Manrope recently for FreeBSD](https://www.freshports.org/x11-fonts/manrope) and tags would be super helpful to keep the package fresh.

Thanks for maintaining this font! It's really nice!

Cheers!
