### ISSUE TITLE
Feature request; Tabular figures

### ISSUE THREAD

**Issue by rymdkapten** [sharanda/manrope#2]
Hi there, 

first of all, amazing font! Been looking for something exactly like this.

My only "issue" is that it currently does not support tabular figures (mono-spaced numbers) which can be useful in spreadsheets and tables for readability.

On the web, this can be enabled by applying a CSS rule;
`font-feature-settings: "tnum";`
or
`font-variant-numeric: tabular-nums;`

I was wondering if there are any plans to support this?

**Comment by sharanda** [comment]
@rymdkapten thank you for your feedback!

Actually, this is something I was concerned about as well. Let me do few tests and see if it performs well, then I will do an update if it's all good.

**Comment by sharanda** [comment]
@rymdkapten I just pushed an update where all digits made as tabular figures. Could you please check if it works correctly? Thanks!

**Comment by rymdkapten** [comment]
Hi again!

It works but it seems to be enabled by default now?
Is it possible to have it as an OpenType feature tag? (tnum in this case)

Sorry for being such a trouble and kudos for the quick response!

**Comment by sharanda** [comment]
@rymdkapten no worries. Yeah, it‘s possible, but are there any problems in having it be default? I made few tests, seems to work well. (I took a reference from the font that I like very much called Akkurat)

**Comment by JohaWeber** [comment]
@sharanda Having tabular figures activated by default would create tabular figures in body copy and therefore would affect legibility. Are oldstyle figures planned for the future? (IMO that is the best option for numbers in body copy.)

**Comment by rymdkapten** [comment]
I tried typing "2018" with a larger font size and found that there now is a lot of space around the "1". While this is exactly what I'd want in a spreadsheet, it affects the legibility in body text.

Another reason is that I think tabular figures are commonly opt-in, so it might be more familiar to other users.

**Comment by sharanda** [comment]
@rymdkapten @JohaWeber Thanks. Yeah, it wasn't very wise... I moved it back to normal and added Tabular Figures as an opentype feature.

For oldstyle figures – it might be an interesting feature to support. However, I can't add it quickly. Maybe I will add it in the next major revision, probably in few months.

<img width="694" alt="screen shot 2018-07-14 at 11 28 28 pm" src="https://user-images.githubusercontent.com/32507483/42725910-4d11eb58-87be-11e8-8c3f-9a74e4c72c7f.png">

**Comment by rymdkapten** [comment]
Works like a charm and looks great! Thank you so much for adding this!

**Comment by sharanda** [comment]
@rymdkapten you're very welcome :-)

P.S.: I feel like it also needs some kerning improvements, will do in next revision

**Comment by Floriferous** [comment]
Can you use this with the fixed-weight variants you get off google fonts? When I use `font-variant-numeric: tabular-nums;`, it doesn't seem to do anything.

**Comment by glowkeeper** [comment]
For anyone else coming here and wondering how to turn this on, this worked for me:
```
font-feature-settings: `'tnum' on`,
```
