### ISSUE TITLE
Would love to see a version with rounded dots

### ISSUE THREAD

**Issue by tettoffensive** [sharanda/manrope#24]
Really loving manrope. I'd love to have alternative glyphs or a variable font choice where the dots for letters like `i`, and `j`, and punctuation like `.` and `,` are rounded. Just to give it a little softer look.

**Comment by sharanda** [comment]
@tettoffensive thanks for the comment! I'll consider that. I had this internal fight in the beginning, but finally decided to stick to that sharp, straight look.

In the meantime, you may try to make this modification in the Glyphs source file

**Comment by tettoffensive** [comment]
I might give it a try when I have more time. I'm pretty comfortable in the Glyphs editor, but I'm not that familiar with the concepts of masters/instances or the proper exporting process.

**Comment by sharanda** [comment]
Closing this issue, because I haven't received enough feedback on this. Personally I feel that rounded don't might conflict with the rest of the font and might trigger much bigger changes.

**Comment by wayne-shih** [comment]
scrolling through the past issues of Manrope and found this ticket 

@tettoffensive I made a rounded dot modified version for a client a wee back
https://github.com/WCYS-Co/HauoraSans

there's a few diacritic issues that's been surfacing up lately and are in the process of patching up, but if you're only after basic latin support -- hopefully this could do the trick for ya 😄 
keep in mind that `k, K, R, G` alongside dot and commas were modified too to fit the project requirements. 

cc: @L-U-C-K-Y, guessing you might be keen too with the thumbs up on the issues?
