### ISSUE TITLE
Add support for Esperanto

### ISSUE THREAD

**Issue by roshavagarga** [sharanda/manrope#29]
Hello and thank you for the amazing font!

I hope you'll take into consideration adding the 12 unique glyphs with diacritics that are required for Esperanto support. You can find more information on them here: 
https://en.wikipedia.org/wiki/Esperanto_orthography#Unicode

**Comment by Stelpjo** [comment]
Yes, this font is amazing and I would love if it had the Esperanto diacritics. As an Esperanto speaker myself it would be very useful.

**Comment by sharanda** [comment]
@Stelpjo @roshavagarga thank you for your feedback. Esperanto support added in v4.5 release
