### ISSUE TITLE
Improve Extended Cyrillic support

### ISSUE THREAD

**Issue by roshavagarga** [sharanda/manrope#30]
Currently, Manrope supports a good amount of Slavic languages, through the extended Cyrillic support that it features. This can be further enhanced by adding the glyphs mentioned below:

Montenegrin Cyrillic:
https://en.wikipedia.org/wiki/Zje
https://en.wikipedia.org/wiki/Sje

Moldovan Cyrillic:
https://en.wikipedia.org/wiki/Zhe_with_breve

Archaic Cyrillic:
In this case specifically Archaic Bulgarian. The below symbols are required if one would like to either imitate or republish documents with the pre-1945 reform Bulgarian alphabet.
https://en.wikipedia.org/wiki/Yat
https://en.wikipedia.org/wiki/Yus - little, big, + both iotifications
Examples of how some of these looked in printed ads:
http://notabene-bg.org/read.php?id=388

**Comment by roshavagarga** [comment]
A further improvement would be to the symbols for [Old Church Slavonic](https://en.wikipedia.org/wiki/Old_Church_Slavonic). Some of these symbols would be covered by the Archaic Bulgarian symbols mentioned above.

The language is only used in churches as far as I'm aware and by scholars. My suggestion is skewed towards using the Cyrillic alphabet, rather than the Glagolitic one, but either way adding all of these would take a lot of time, just making you aware of it as an option. Personally I'm only interested in the ones I mentioned above.

**Comment by davelab6** [comment]
A user wrote me via Google Fonts,

> Please add ₽ ruble into font family Manrope. Thanks!

**Comment by roshavagarga** [comment]
@davelab6 It's been available for some time, as can be seen @ https://manropefont.com in Glyphs

**Comment by roshavagarga** [comment]
@sharanda As can be seen [here](https://bekl.org/), there is an initiative to improve the current official keyboard layout standard for Bulgarian. This initiative includes the addition of the aforementioned yus and yat and their variations, as well as a few others, which I have missed, but are required for scientific texts (probably for linguists) : а̀, ъ̀, о̀, у̀, ѐ, ѝ, ю̀, я̀ (both capitalized and noncapitalized?).
Yus and yat should go into the local Bulgarian Cyrillic, but I'm not so sure where the others should go.

**Comment by sharanda** [comment]
Haven't received enough feedback on providing more extended Cyrillic support. Sorry, it seems unnecessary.

**Comment by roshavagarga** [comment]
@sharanda Here's your direct feedback:
1. Zhe with breve is required for Moldovan written in the unrecognized state of Transnistria in Moldova.
2. Zje and Sje are required if you want support for Montenegrin Cyrillic.
3. Yat, iotified yat, cursive yat, big yus, big iotified yus, big yus, small iotified yus, small yus are required for full pre-1945 Bulgarian support and scientific paper support.
4. а̀, ъ̀, о̀, у̀, ѐ, ѝ, ю̀, я̀ are required for Bulgarian for linguists and edge cases where you need to show where the emphasis is in a word. Bulgarian would require some of there in the local written variety.

Population of Transnistria - 470 000~
Population of Bulgaria - 7 000 000~
Population of Montenegro - 620 000~

I can't speak about Montenegrin Cyrillic or Moldovan Cyrillic, but personally if you implemented the changes for Bulgarian, I'd be able to use the font for work-related things. If you don't want to bother with doing it, that's within your rights.

**Comment by sharanda** [comment]
@roshavagarga just saying: community haven't shown enough interest in this. And as always: this is an Open Source project. You can add any desired changes, and even submit Pull Request to be implemented in the master version.
