### ISSUE TITLE
Fix omission(s) in supported languages

### ISSUE THREAD

**Issue by roshavagarga** [sharanda/manrope#31]
Your current list of supported languages (as seen on manropefont.com) is missing these, and probably more:
- Basque
- Breton
- Dutch
- Faroese
- Maltese
- Monégasque
- Occitan
- Romansh
- Rusyn
- Spanish
- Ukrainian

**Other errors:**
There is an 'Iiish' between the languages starting with S. I'm guessing this is/was Irish? Should be removed.

**Comment by sharanda** [comment]
@roshavagarga thanks for reporting. I'm pretty sure it fully supports at least Danish, Spanish, Ukrainian. Let me double-check why those are missing on the website.

**Comment by roshavagarga** [comment]
It supports all of the above, they're just not listed. Also, Dutch not Danish, unless you meant Faroese which is a different Germanic language spoken in the Faroe islands and parts of Denmark. Thanks for the great work!

**Comment by sharanda** [comment]
@roshavagarga Thanks! Added: "Basque, Dutch, Spanish, Ukrainian". There are many more minor languages this font supports as well. I'm trying to keep that list on the website clear and short... Added "And others..." in the end to avoid misleading.
