### ISSUE TITLE
Expand currencies

### ISSUE THREAD

**Issue by roshavagarga** [sharanda/manrope#33]
Currently, Manrope supports a number of the bigger currencies, but the addition of the symbols shown underneath would add a wider coverage.

1. Franc (₣) - Adds coverage for the Swiss franc, CFP franc, Comorian franc, Congolese franc, Djiboutian franc and Guinean franc. 
2. Won (₩) - adds support for the North Korean, South Korean and Old Korean Won.
3. Indian rupee (₹).
4. Philippine peso (₱).
5. Israeli new shekel (₪).
6. Turkish lira (₺).
7. Mongolian tögrög (₮).
8. The Bitcoin cryptocurrency (₿).

There are a number of other unique currency symbols, information on which can be found here:
https://en.wikipedia.org/wiki/Currency_symbol

**Comment by sharanda** [comment]
@roshavagarga thanks! Added new currencies with v4.5 release
