### ISSUE TITLE
Improve support for Catalan

### ISSUE THREAD

**Issue by guillemch** [sharanda/manrope#34]
There is currently a bug in the letter spacing between letters and the middle dot (·) [U+00B7](https://www.compart.com/en/unicode/U+00B7), which in the case of the Catalan language is very important, as the combination `l·l` is considered a single letter https://en.wiktionary.org/wiki/l%C2%B7l#Catalan 

<img width="908" alt="Screenshot 2019-12-09 at 12 44 49" src="https://user-images.githubusercontent.com/19528251/70433319-b64fae00-1a81-11ea-851c-08751d73c4c0.png">

As can be seen in the picture, the spacing between the Ls and the dot is too wide and very noticeable.

We would really appreciate it if you could fix this issue as we want to use Manrope for a project.

Thank you

**Comment by sharanda** [comment]
@guillemch thanks for reporting! periodcentered and periodcentered.case were fixed. Please double check. *testing web-page might be updated later due to server cache

**Comment by guillemch** [comment]
That's great! Thank you!
