### ISSUE TITLE
Possible to get this on a CDN?

### ISSUE THREAD

**Issue by MastaCoder** [sharanda/manrope#35]
It'd be really cool if we can get the font on some sort of CDN like cdnjs.com (https://github.com/cdnjs/cdnjs)

**Comment by sharanda** [comment]
@MastaCoder thanks for reaching out. I will definitely consider this.

I need to learn more about font-face usage from external servers/cdn. As I know, there are some restrictions applied and need some special settings on the server side.

Would appreciate if someone can help to clarify this topic.

**Comment by sharanda** [comment]
I'm closing this issue, because I don't know how to deal with it. Let's hope for Google Fonts approval.

**Comment by roshavagarga** [comment]
@sharanda I can look into this on my own time if you want some help, since I'm guessing a good amount of developers and users would also prefer to have this outside of Google's territory, due to privacy concerns :)
