### ISSUE TITLE
Manrope variable font smaller than previous version

### ISSUE THREAD

**Issue by tettoffensive** [sharanda/manrope#36]
I was testing out the new manrope variable font file in the master branch in Sketch and noticed that when I switch to it (using the same font size: 40pt and font weight: semibold), the fonts are different sizes. The new one is smaller.

Is this a bug or is there a way for me to switch seemlessly without seeing changes?

![Screen Shot 2020-01-10 at 11 53 26 AM](https://user-images.githubusercontent.com/5884119/72182200-d71c6380-339f-11ea-856a-721ffeab3fdb.png)

**Comment by bghryct** [comment]
I believe this is from the typolinegap adjustment commit dc0fd64
Haven't looked carefully at it, but that's a possibility.

**Comment by sharanda** [comment]
@tettoffensive we've fixed some mistakes in the metrics that made Manrope appear bigger than it should be. Sorry for inconvenience. Please, adjust your styles.
