### ISSUE TITLE
Missing Greek I with accent

### ISSUE THREAD

**Issue by kosvrouvas** [sharanda/manrope#37]
Hi, if you type the Greek I with an accent it turns as an I with diaeresis.

You can see that the accent is missing from the chart below, and there are two identical glyphs with diaeresis.

![εικόνα](https://user-images.githubusercontent.com/3307723/74240623-0bf34180-4ce3-11ea-8d59-590fce7d5f0e.png)

**Comment by sharanda** [comment]
@kosvrouvas thanks for reporting about this issue. I've already fixed together with other minor adjustments. After a few tests I'll update it shortly in the repository and the website.

**Comment by sharanda** [comment]
Fixed in v4.5 release
