### ISSUE TITLE
Bad "i" letter rendering in Chrome browser

### ISSUE THREAD

**Issue by mdudek** [sharanda/manrope#38]
The letter "i" rendering in Chrome browser is not good in size of 20px (without page zoom). There is missing a dot space and it looks like "l"  rather than "i" letter.  The 'small j' letter looks good.

Here is a screenshot of "iii jjj" text rendered in Chrome:
![image](https://user-images.githubusercontent.com/5558549/75766215-13859380-5d41-11ea-8532-bcd847890fd3.png)

**Comment by sharanda** [comment]
@mdudek thanks for reporting about this issue. Is it on Windows PC? Are you using the latest version from this repository or manropefont.com ? Are you sure it's not capital i /I #0049 ? Please let me know.

**Comment by sharanda** [comment]
@mdudek I couldn't repeat it on Windows Chrome... Which font format(OTF/TTF/Variable TTF/WOFF2?) and thickness you're using?

**Comment by mdudek** [comment]
Thanks for help, I have already found source of the problem. There was used probably wrong converted woff format of the font. I have updated this font file and it is working fine right now.

btw: I'm using Windows PC
