### ISSUE TITLE
Capital eszett (ẞ) design

### ISSUE THREAD

**Issue by Stelpjo** [sharanda/manrope#39]
Despite that I am not a German speaker by any means, I still have an appreciation for its orthography, particularly the eszett: ß. However, its capital form, ẞ, is often not designed well in fonts. In Manrope, it seems a bit too narrow and similar to the lowercase form.

[Here's a Twitter post](https://twitter.com/CatharsisFonts/status/1192483066226323457) that shows how it could potentially be improved, as well as [an article](https://typography.guru/journal/capital-sharp-s-designs/) showing some different designs for the letter.

I don't mean to be too critical. Even though some improvements could be made, as it stands I think Manrope is a really great font! In any case, I hope you consider this. Thank you.

**Comment by sharanda** [comment]
@Stelpjo thanks! That's very helpful. I've adjusted this letter in v4.5 release.
<img width="126" alt="Screenshot 2020-03-14 at 1 02 06 PM" src="https://user-images.githubusercontent.com/32507483/76675471-cd5bea00-65f4-11ea-983a-620874c11c8d.png">
