### ISSUE TITLE
Vertical metrics in font metadata

### ISSUE THREAD

**Issue by jacobp100** [sharanda/manrope#42]
I've noticed the vertical metadata in this font is a bit off. I'm using https://opentype.js.org/glyph-inspector.html to compare the vertical metadata of this font to Roboto (which has correct vertical metadata)

Roboto

<img width="500" alt="Screenshot 2020-04-23 at 15 31 46" src="https://user-images.githubusercontent.com/7275322/80111411-c58a5080-8577-11ea-87b3-924c86bedcd1.png">

Manrope

<img width="492" alt="Screenshot 2020-04-23 at 15 32 00" src="https://user-images.githubusercontent.com/7275322/80111416-c6bb7d80-8577-11ea-9d94-514dac19c137.png">

We're using React Native, and we've found the line heights of fonts with incorrect vertical metadata can cause text to be clipped or incorrectly vertically centred

**Comment by sharanda** [comment]
@jacobp100 thanks for reporting about this issue. From which source you're using the fonts? Website/GitHub/google fonts?

**Comment by jacobp100** [comment]
I tried both GitHub and Google Fonts

**Comment by sharanda** [comment]
@jacobp100 I've tried to import OTF/TTF fonts with other software and found that vertical metrics are preserved in the font data. I'm not aware how https://opentype.js.org/ works, if there's a more specific information on what exactly is missing in Manrope, I might give a second try to fix it. Until then I'm closing this issue.

**Comment by jacobp100** [comment]
What software are you using to develop on?

**Comment by sharanda** [comment]
> What software are you using to develop on?

Glyphs https://glyphsapp.com/
