### ISSUE TITLE
Italic support

### ISSUE THREAD

**Issue by NetOperatorWibby** [sharanda/manrope#43]
Would be a nice to have.

**Comment by Floriferous** [comment]
Is there already a way to get an italic version for designer tools or print tools? Not sure how these variable fonts work

**Comment by sharanda** [comment]
@NetOperatorWibby @Floriferous unfortunately, I'm not a fan of Italic Sans-Serif fonts... I don't like any of them... Maybe I'll design a cursive font some day, but that would be an entirely different font.

I would recommend to avoid it, but you can give a try to Faux italics. For example, html and photoshop:
<img width="665" alt="ps" src="https://user-images.githubusercontent.com/32507483/80914105-15d58f80-8d7c-11ea-8ee2-1862479ee6c0.png">
<img width="779" alt="css" src="https://user-images.githubusercontent.com/32507483/80914106-179f5300-8d7c-11ea-9b12-c275153094a4.png">

**Comment by Floriferous** [comment]
It only seems to work on Safari, it doesn't work in Google Chrome on my machine (mac OS), is this a browser issue, or can you do something about it?

**Comment by malte-v** [comment]
FYI https://github.com/malte-v/manrope-italic

**Comment by roshavagarga** [comment]
@sharanda Would you be up for reconsidering this in any form? Your font is ideal for use in eBook Readers which need italics support - right now if I try to use it, I get perfect text except when there's a word in italics - that just pops up in a different font...

**Comment by alejandrosantana** [comment]
+1 to give italics a try.
Sometimes you cannot avoid italics. In Spanish italics should be used in foreign words used inside a text, and there are many.
When trying to force faux-italics in LibreOffice, for example, the word is slanted and almost overlaps with the next one.
![manrope_italics_in_libreoffice_overlap](https://user-images.githubusercontent.com/3707483/107033364-7b482800-67b5-11eb-90ec-50e31ae73f13.png)

**Comment by cssobral2013** [comment]
@sharanda & @NetOperatorWibby - I'm proposing italics for this font. See #69 and please accept it.
