### ISSUE TITLE
Fonts are broken upon install in Windows

### ISSUE THREAD

**Issue by daveranan** [sharanda/manrope#44]
Installing the font in windows results in installed Regular and Bold font weights, the rest font weights are installed as Regular font weights and are not recognized by system. 
![image](https://user-images.githubusercontent.com/6812854/80872697-3668f100-8c79-11ea-8e0e-7b69ca2ab3e3.png)
(As you can see, "light" font weight is recognized as "regular")

Also the fonts somehow get installed into C:\Users\{username}\AppData\Local\Microsoft\Windows\Fonts location which becomes protected by system, so you can't uninstall the font unless you go into safe mode and remove it through font manager. In non-safe mode, uninstall results in Font manager crash, and files are protected by system.

**Comment by sharanda** [comment]
@daveranan thanks for reporting about this issue. I see that the file name looks correct in your font file path, but it sounds like you're trying to use the variable font format in the system level, which cannot recognize all the weights and renders all as Regular.

Did you download it from GitHub/Manropefont.com/Google Fonts?

I know for sure that OTF format works correctly on Windows. Unfortunately, I'm unable to test it on an actual Windows machine. Could you try to use OTF format, and see if the issue still exists? Thanks.

**Comment by Andrei-Stakov** [comment]
This issue also happened to me, and it was only specific to the .ttf fonts from Google Fonts. Tested both the .otf and .ttf files from Github and it turns out fine.

![image](https://user-images.githubusercontent.com/16612525/81464897-e4cbe380-91ef-11ea-93d0-1ffc3861e797.png)
[**Left** - _Github's_; **Right** - _Google's_]
Did Google modified the files by compressing them?

Haven't tested the ones from manrope.com (my ISP seems to hate your server :( ), but if it's the same files with Github's, it'll probably be fine.

**Comment by sharanda** [comment]
@Andrei-Stakov thanks for reaching out. Let's try to fix it. Yes, there was a minor update after we submitted the font to Google Fonts. I plan to push one more minor adjustment, and then submit to Google again.

@bghryct could you look into this? Do you have any idea why this might happen? Maybe @m4rc1e could help?

**Comment by ogio** [comment]
Hi @sharanda, first of all, thank you for beautiful font, one of the best!
Having same problem with font and it is a little bit strange issue so here is some situations:

2 PC, font installed here from github:
- one PC have issues with same Regular and ExtraBold weights
- another PC have issues with Light that is same like Medium

On both PC work is on Figma (browser and app) and same issues.
On OSX, fonts are not having any issues.

Any plan for update? Fix?

**Comment by m4rc1e** [comment]
The family which is downloadable from Google Fonts should now work.

The issue was each font had the same name table nameID 3 record, when they're meant to be unique for each font.

**Comment by ogio** [comment]
![image](https://user-images.githubusercontent.com/3105571/85959410-b15e3780-b99c-11ea-89aa-b154064d850e.png)

Just downloaded, even now i dont have anything except Regular and Bold in Figma !?

**Comment by ogio** [comment]
I install now from github font and it is good, i have finally all variants without issues. Before new install, i delete present fonts... True that in Fonts Win app preview of fonts is not good, but Figma App is recognizing it finally good.

![image](https://user-images.githubusercontent.com/3105571/85959596-a8219a80-b99d-11ea-80d7-075b743ae6d8.png

p.s. still on Google is not last version of font or font with issues

**Comment by sharanda** [comment]
Looks like Google Fonts fixed this issue

**Comment by stevebaum23** [comment]
@sharanda 

Google Fonts is still hosting a version of the font with this issue. I downloaded the font today and when installing on Windows 10, it's showing all the styles as regular. You can see the timestamps are all from 2019 like in @Andrei-Stakov screenshot above.

![image](https://user-images.githubusercontent.com/50835640/110389088-9fec2580-8029-11eb-8130-50d54336a4c4.png)

![image](https://user-images.githubusercontent.com/50835640/110389351-05d8ad00-802a-11eb-95fd-6958a1248d28.png)

**Comment by sharanda** [comment]
@stevebaum23 sadly, Google re-compiles my font files. I've never had such issue with my own files hosted on https://manropefont.com/manrope.zip
Until Google Fonts resolve this issue I strongly suggest to use a version from Github or manropefont.com

**Comment by iamfrankeu** [comment]
I bumped into this issue today when I tried to open my previous Adobe XD file created on a MacOS into my Windows. First I installed the version from Google Fonts, which seems to be working fine on Adobe XD / Mac but received the same issues as in the comment above on a Windows machine. The following steps solved this issue for me:

1. Make sure all your Adobe CC programs are shut down
2. Remove the files from your library `C:\Windows\Fonts`
3. Restart your Windows (I know it sounds silly, but it did the trick for me)
4. Install the fonts from a source like @sharanda said in his comment https://github.com/sharanda/manrope/issues/44#issuecomment-793248552

I hope it helps someone out.

**Comment by jared-rice** [comment]
Just wanted to say still similar issues for me - Google Fonts Download messed up the font files, showing multiple regulars. Downloading from the original site worked best.

However, I am experiencing another issue related to ligatures not working at all - at least in Figma. It doesn't even register the different characters in the ligature preview. Other typefaces I have with ligatures are working just fine.

Could this be an issue with the current version of font files downloaded from the website?

**Comment by sharanda** [comment]
The issue is related to Google algorithms I have no control over. There's no issue on the font version from the website or GitHub.

**Comment by bergerb-com** [comment]
I feel like this could be the right place to post this:
Google's Font worked on Windows 10, but not on Windows Server 2016.
I only got the Extra Light Font. (W2016 told me inside `C:\Windows\Fonts`, that it only has the ExtraLight-Version. Also eg. in WordPad, only Manrope ExtraLight was selectable)

With your font, it works now flawlessly: https://www.gent.media/assets/manrope/manrope.zip

**Comment by sharanda** [comment]
@bergerb-com thank you for your feedback. There are many issues with the version on Google Fonts. Unfortunately, I can do nothing with how Google post-process the font, but suggest to use a version from this repository or gent.media/manrope website
