### ISSUE TITLE
500, 700, and 800 font weights not working for variable font

### ISSUE THREAD

**Issue by jeremylanger** [sharanda/manrope#45]
Hello,

First off, thank you for this amazing font. I love it. I'm working on integrating the variable font, but I'm having issues with setting the `font-variation-settings: 'wght'` for 500, 700, and 800 font weights. When these 'wght' values are set, it displays as the 'wght' 200 would.

On another note, why don't weights between the major 100-increments work? For example, 350 doesn't work, and it displays as 200 instead. I thought that was part of what a variable font includes.

I'm using the latest version of Chrome for this testing by the way. Thanks in advance.

```
@font-face {
	font-family: 'Manrope';
	src: url('manrope-variable.ttf') format('truetype-variations');
	font-weight: 200 800;
	font-style: normal;
}
h1 {
	font-family: 'Manrope';
	font-variation-settings: 'wght' 800;
}
```

**Comment by sharanda** [comment]
@jeremylanger thanks for reporting about this issue. Can I test in online somewhere?

It sounds like system and embedded font conflict. Can you try to give your font-family a different name? On manropefont.com I've done it like this:

```
@font-face {
    font-family: 'Manrope VF';
    src: url(/assets/fonts/variable/ManropeGX.ttf) format("truetype-variations");
    font-style: normal;
    font-variation-settings:'wght' 500;
    font-variation-ligatures:normal;
    font-weight: 200 800
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-ExtraLight.woff2) format("woff2");
    font-weight: 200
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-Light.woff2) format("woff2");
    font-weight: 300
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-Regular.woff2) format("woff2");
    font-weight: 400
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-Medium.woff2) format("woff2");
    font-weight: 500
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-SemiBold.woff2) format("woff2");
    font-weight: 600
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-Bold.woff2) format("woff2");
    font-weight: 700
}

@font-face {
    font-family: Manrope;
    src: url(/assets/fonts/web/Manrope-ExtraBold.woff2) format("woff2");
    font-weight: 800
}

body,html,input {
    font-family: 'Manrope VF',Manrope;
    font-variation-settings: 'wght' 500;
}
```

**Comment by jeremylanger** [comment]
@sharanda Thank you for your help and posting that code. That really got me on the right track. It turned out to be a caching issue 🤦‍♂️ Thanks again and have a good one!
