### ISSUE TITLE
Bad font line height rendering in Ie 11

### ISSUE THREAD

**Issue by Unknow-max** [sharanda/manrope#47]
Hi,
First of all I want to thank you for the fantastic font you made. 

I noticed an issue About the font line-height rendering in Ie 11. See there:

![Annotazione 2020-06-02 145953](https://user-images.githubusercontent.com/59534318/84195315-a18abc00-aa9e-11ea-8dae-f58e79346383.png)

This Is the normal expected behavior, look very good (note that I have applied a really small padding bottom on the h3 title, 3px).

This instead, Is the Ie 11 rendering:

![Annotazione 2020-06-02 145842](https://user-images.githubusercontent.com/59534318/84195461-e7478480-aa9e-11ea-9fac-98fb6106efb6.png)

As you can see the title have an incorrect line height.

See also that image:

![Annotazione 2020-06-02 145930](https://user-images.githubusercontent.com/59534318/84195553-0fcf7e80-aa9f-11ea-9a73-5a7c49b42edb.png)

The Button text is shifted to the bottom even is supposed to be centered inside of it.

The default line height is 1.15, and I founded this bug only on Ie (11 in this case, not tested in older versions).

**Comment by sharanda** [comment]
@Unknow-max thanks for reporting about this. Looks like you're using a much older version of the font. This issue was fixed previously, please update the font to the latest version

**Comment by Unknow-max** [comment]
@sharanda Thank you very much!
I installed the font About One years ago and it didn't occur to me to update it 😅
