### ISSUE TITLE
Font issues using Figma (Windows10)

### ISSUE THREAD

**Issue by ogio** [sharanda/manrope#48]
Hi @sharanda, first of all, thank you for beautiful font, one of the best!
Having same problem with font and it is a little bit strange issue so here is some situations:

2 PC, font installed here from github:
- one PC have issues with same Regular and ExtraBold weights
- another PC have issues with Light that is same like Medium

On both PC work is on Figma (browser and app) and same issues.
On OSX, fonts are not having any issues, everything works perfectly.

Any plan for update? Fix?

**Comment by capsula-io** [comment]
Same problem, not working in Figma

**Comment by ogio** [comment]
After couple of deleting and new installations, conclusion is that font on Google is not good, and version from git is working well.

![image](https://user-images.githubusercontent.com/3105571/85959669-03538d00-b99e-11ea-808b-025b9d132b45.png)
