### ISSUE TITLE
Problem with font usage on iOS 

### ISSUE THREAD

**Issue by ogio** [sharanda/manrope#49]
Hi, me again :)

When developer in xCode create screens, font is visible like it should, including font weights... When he "push" view to device, font weights are not visible. With other fonts that we try (ex. SF Display Pro, Roboto) there is no problem with view. 

![Screenshot 2020-07-01 at 13 16 51](https://user-images.githubusercontent.com/3105571/86238067-34e67700-bb9d-11ea-8c11-9f9b1eba18e5.jpg)
Image: left device screen, right xCode screen (look just Heading weights)

Please help, I want to use this font for full project on all platforms but definitely there are issues with usage.
Somebody have same issues?

**Comment by sharanda** [comment]
@ogio Hi, I'd be happy to help, but I have no idea how can I test it haha

Let's try to identify where it comes from:

1. Are you using the latest version of font from Github/manropefont.com or Google Fonts?
2. Which format are you using Variable/TTF/OTF?
3. Are sure the font is deployed on the device, and xCode isn't using a font installed in your system? 
4. Are there any related errors/warnings in the logs?

**Comment by ogio** [comment]
Hi Michael, here are answers:
1) Github
2) we try with TTF and OTF, no differences. Didnt try with Variable one, we will do it asap
3) I will check with dev, but he is making regular procedure - first installing font on system, then putting into project font folder, making integration with project and then making preview
4) Will check too and come here with results.

Thank you for fast answers

**Comment by sharanda** [comment]
> 2. we try with TTF and OTF, no differences. Didnt try with Variable one, we will do it asap
TTF and OTF are much safer to use. Variable fonts support is still very rare

> 3. I will check with dev, but he is making regular procedure - first installing font on system, then putting into project font folder, making integration with project and then making preview
I'd suggest to delete font from the Mac OS system, make sure the font is packaged within the project and displayed correctly in the xCode. Then try to deploy on a real device again

**Comment by ogio** [comment]
@sharanda 
2. we try variable, same thing
3. regular procedure, developer have experience, first time he have problem with integration
4. no error logs

**Comment by ogio** [comment]
> > 1. we try with TTF and OTF, no differences. Didnt try with Variable one, we will do it asap
> 
> TTF and OTF are much safer to use. Variable fonts support is still very rare
> 
> > 1. I will check with dev, but he is making regular procedure - first installing font on system, then putting into project font folder, making integration with project and then making preview
> 
> I'd suggest to delete the font from the Mac OS system, make sure the font is packaged within the project and displayed correctly in the xCode. Then try to deploy on a real device again

We try this too, no changes...

**Comment by ogio** [comment]
@sharanda Problem has been solved. 

From dev report, there is bug with new versions of xCode where errors of font inegration wasnt visible. Regular work of integration now include manual reference connections in xCode project. It is weird because if font is not integrated good, it should not be visible good in xCode project too.. 

At any case, now everything is working good and our project will use your beautiful font ;)
Thank you for your support! Keep up the good work!
