### ISSUE TITLE
Strange rendering of Manrope in website (joomla + yootheme + google fonts)

### ISSUE THREAD

**Issue by Balbina** [sharanda/manrope#51]
You guess which reason could cause this "white" on letters like the "e"?
https://www.lacocteleramusic.com/

**Comment by sharanda** [comment]
> You guess which reason could cause this "white" on letters like the "e"?
> https://www.lacocteleramusic.com/

Thanks for reporting about this issue. Looks like other letters like /A also have this problem. Unfortunately, there's no direct contact with Google engineers. Probably, it would take a while to fix this issue... If possible, please use self-hosted font-files from https://manropefont.com/ or this Github project

**Comment by Balbina** [comment]
Thanks for your fast answer
And congrats for this really nice font.
I update directly your fonts to the server and now looks perfect

Thanks :)

**Comment by Lapin** [comment]
I also had awfully wrong rendering with Google Fonts variation, but updating it to this current version fixed ninety percent :)

On my mac I can clearly see it's being rendered perfectly but there's still a bit jaggyness on my regular 1920x1200 resolution monitor.

**Retina Looks**
<img width="71" alt="Screenshot 2020-07-20 at 19 35 43" src="https://user-images.githubusercontent.com/1576470/87962899-9759d580-cac0-11ea-9aca-cb4f3016871a.png">

**Jaggy Looks**
![Screenshot 2020-07-20 at 19 35 33](https://user-images.githubusercontent.com/1576470/87962902-97f26c00-cac0-11ea-97e8-8fa9b8081578.png)

**Comment by sharanda** [comment]
Looks like Google Fonts fixed this issue
