### ISSUE TITLE
Ordinal indicator (Portuguese, Spanish, Italian...) are too big

### ISSUE THREAD

**Issue by diegomath** [sharanda/manrope#52]
Hi Sharanda,

I'm using this typo in a site and it's getting amazing! I saw that **ordinal indicators ª and º** (very common in Portuguese, Spanish, Italian...) l. It looks like normal chars like a and o and should be smaller.

https://en.wikipedia.org/wiki/Ordinal_indicator.

I hope It will be updated in next release.

Regards,

Diego

**Comment by sharanda** [comment]
@diegomath thanks for your comment. Will see what I can do, will try to learn a bit more about it.

**Comment by sharanda** [comment]
@diegomath it's fixed in 4.503. Please check? Manropefont.com will be updated later.

**Comment by diegomath** [comment]
Thanks a lot Sharanda, I saw in the site and it looks perfect!
