### ISSUE TITLE
More weights?

### ISSUE THREAD

**Issue by ZachTheDev** [sharanda/manrope#54]
I would love to see more weights! Specifically 900 and 1000 (Black, and ExtraBlack (or sometimes called Heavy))
I downloaded the Glyphs app to give it a shot but realized I don't have the skill to change the master.

Is there any chance you would be willing to work on more weights?

Thanks!

**Comment by sharanda** [comment]
Thanks for your comment. As I know, interpolations can be added only between 2 extremes. It means that at this point it would be too much work to add a new thicker extreme... And personally I don't feel like such a semi-condensed font should be bolder than it's now.

**Comment by mushon** [comment]
@sharanda I understand your answer on the subject but I was wondering what would it take or how much would it cost to commission a black master that would extend the weight variations of this beautiful font?
