### ISSUE TITLE
Localized forms for different language systems in the same lookup

### ISSUE THREAD

**Issue by dscorbett** [sharanda/manrope#55]
The 'locl' substitution for Turkic languages (`i` → `i.loclTRK`) is in the same lookup as the 'locl' substitutions for Romanian and Moldovan (`Scedilla` → `uni0218` etc.). That means any text tagged as Turkish will also be localized as Romanian and vice versa.

Similarly, the 'locl' substitutions for Bulgarian and Serbian are mixed into the same lookup.

**Comment by sharanda** [comment]
@dscorbett thanks for reporting about this. As I understood, you advice is to add specific .loclTRK substitutions?

**Comment by dscorbett** [comment]
I’ve seen other fonts with the same bug, so I suspect it is a problem with your version of Glyphs. However, you should be able to work around it. My advice is to split `locl_latn_0` into two lookups: one for Romanian/Moldovan and one for the Turkic languages. Similarly, split `locl_cyrl_0` into two lookups: one for Bulgarian and one for Serbian.

**Comment by sharanda** [comment]
@dscorbett Current setup looks like this:

languagesystem latn TRK;
languagesystem latn ROM;
languagesystem latn MOL;

languagesystem cyrl BGR;
languagesystem cyrl SRB;

I guess it's not related to Glyphs version, I'm just using default latin for Turkic. The issue is that there's no localised version for Turkic languages, is it what you mean?

**Comment by dscorbett** [comment]
It looks like this issue has been fixed since I opened it. Maybe you upgraded your Glyphs version. The problem was that Romanian text would be localized as Turkish and vice versa because they shared the same 'locl' lookup. Now each language system has its own 'locl' lookup, so there is no problem.
