### ISSUE TITLE
Error in displaying the combination of characters "д,"

### ISSUE THREAD

**Issue by AndTem** [sharanda/manrope#56]
When displaying a combination of characters "д," there is no distance between characters.
[Example from google fonts](https://fonts.google.com/specimen/Manrope?query=manrope&preview.text=%D0%BA%D0%BE%D0%B4,%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9&preview.text_type=custom#glyphs):
![image](https://user-images.githubusercontent.com/23665108/95339810-2656dc80-08bd-11eb-8d8c-78c3434482f3.png)

**Comment by sharanda** [comment]
@AndTem thanks for reporting about this. I will try to fix it soon

**Comment by sharanda** [comment]
@AndTem this issue has been fixed in 4.504. Google fonts and Manropefont.com will be updated later.

**Comment by AndTem** [comment]
@sharanda thanks you!
