### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by NetOperatorWibby** [sharanda/manrope#57]
Since Apple doesn't allow the usage of their San Francisco typeface as a webfont, I've found Manrope to be an aesthetically-pleasing alternative. I'm going to use it for a project (well, I'm evaluating it...just remembered this doesn't have italics). I hope will get noticed and typography contributes a lot to what we look at and use every day.

Anyhoo, I think there should be a way for people to fund further development.

**Comment by sharanda** [comment]
No donations needed, but thanks.

Repeat of older issue: https://github.com/sharanda/manrope/issues/43
