### ISSUE TITLE
Weird ugly appearance of cyrillic version on Apple devices

### ISSUE THREAD

**Issue by nt4f04uNd** [sharanda/manrope#58]
Android and other platforms:
<div>
<img width="33%" src="https://user-images.githubusercontent.com/39104740/97106388-529e9580-16d2-11eb-8941-54985fb78dbf.jpg">
<img width="33%" src="https://user-images.githubusercontent.com/39104740/97106389-53372c00-16d2-11eb-907f-d38cafbccfb2.jpg" >
<img width="33%" src="https://user-images.githubusercontent.com/39104740/97106390-53cfc280-16d2-11eb-8eb2-0c62865b89d5.jpg">
</div>

iOS:
<div>
<img width="33%" src="https://user-images.githubusercontent.com/39104740/97106392-56cab300-16d2-11eb-9931-faecdccd87de.PNG">
<img width="33%" src="https://user-images.githubusercontent.com/39104740/97106393-57634980-16d2-11eb-8247-234e1fc401d2.PNG">
<img width="33%" src="https://user-images.githubusercontent.com/39104740/97106394-57fbe000-16d2-11eb-9c84-9d58a2c3024b.PNG">
</div>

Is it inteded, and if so, why and how do I change that?

**Comment by sharanda** [comment]
@nt4f04uNd please use self-hosted font files from Github or Mantopefont.com instead of Google Fonts version.

**Comment by nt4f04uNd** [comment]
@sharanda yep, self-hosted did help, thanks. Why is that though?

**Comment by sharanda** [comment]
@nt4f04uNd not sure. For some reason Bulgarian Cyrillic used for regular Cyrillic letters specifically on iOS14 if you’re using Google Fonts version. As @bghryct helped to check: locl feature implemented exact same way in both versions. Today I’ve noticed iOS 14.1 update released. Looks like Apple have fixed the bug.
![DBF91FB5-898A-4880-8D69-4EB9C26F23B9](https://user-images.githubusercontent.com/32507483/97250553-2c4b3800-1841-11eb-8cb3-20ebb8b4ac4f.jpeg)
