### ISSUE TITLE
Issue with appearance of crossbars on 'A' and 'e' while in OS Preview

### ISSUE THREAD

**Issue by MLuk90** [sharanda/manrope#59]
I've noticed that when previewing pdfs that have used Manrope where the text has not been outlined, letters that use crossbars such as capital A and lowercase E have small holes appear in them, like there is some sort of pathfinding issue. This only seems to happen when using Apple's Preview program to view things, but can be quite distracting and offputting. Is there a fix for this?

Examples attached,

thanks
![Screen Shot 2020-10-27 at 11 01 13](https://user-images.githubusercontent.com/73530423/97293438-94e7e400-1844-11eb-958f-9e8d78e1d4de.png)
![Screen Shot 2020-10-27 at 11 01 16](https://user-images.githubusercontent.com/73530423/97293443-95807a80-1844-11eb-9cdd-7bf217b17f4e.png)

**Comment by sharanda** [comment]
@MLuk90 it seems Apple's preview software don't pay attention to path direction - which has to be preserved for the variable font format. The easiest way to fix it is to use OTF/TTF version of the font from Github or https://manropefont.com - because those were exported with 'remove-overlap' option. Thus, there would be no path direction issue.

**Comment by MLuk90** [comment]
@sharanda thank you I will try that now. And thank you for the font, I think it's beautiful!

> @MLuk90 it seems Apple's preview software don't pay attention to path direction - which has to be preserved for the variable font format. The easiest way to fix it is to use OTF/TTF version of the font from Github or https://manropefont.com - because those were exported with 'remove-overlap' option. Thus, there would be no path direction issue.

**Comment by sharanda** [comment]
The issue is related to third party software algorithms.
