### ISSUE TITLE
Is there going to be programming ligature support?

### ISSUE THREAD

**Issue by karntrehan** [sharanda/manrope#6]
Firstly, beautiful font!

I am not sure if programming is one of the usecases for this font, but are you looking at adding programing ligature support, or is it already added? Thanks!

**Comment by sharanda** [comment]
@karntrehan Thanks! Web-pages were the main purpose. Do you mean ligatures like https://github.com/tonsky/FiraCode ?
Not sure why do you need it for a non-monospaced font. Can you elaborate?

**Comment by karntrehan** [comment]
Hie, thanks for the reply.
Yes, ligatures exactly like Firacode.
 Usecase: Just wanted to try out the font for programming because it looks beautiful. No worries if programming is not the use case.

**Comment by sharanda** [comment]
@karntrehan I actually would love to make a monospaced version, but not any time soon... 🤔
