### ISSUE TITLE
Problem with ios 14.2

### ISSUE THREAD

**Issue by dmitri-sud** [sharanda/manrope#61]
Hi. I saw this problem in closed cases. But it seems it back again. 
On all apple iphones with 14.2 ios. Funny thing that on google fonts website also wrong Cyrillic look. 
I tried to to run font from my server, downloaded this font from this website and from original website. But i had same problem. 
Maybe you can give some advices for me? Thank you

**Comment by sharanda** [comment]
The issue is related to 3rd party algorithms, but looks like Google has fixed it. If it appears again, please use a version from Github or manropefont.com.
