### ISSUE TITLE
Letter "m" not appearing properly

### ISSUE THREAD

**Issue by SJordd** [sharanda/manrope#62]
I'm using this font on my website (still building, not live yet), and I've noticed the letter "m" consistently appears glitched. It appears to be a problem with bold or more heavily-weighted text. See screenshots. Is there any way to fix this? Thanks!

![Manrope_letter-m_2](https://user-images.githubusercontent.com/75579913/101287267-37d53b80-37bd-11eb-8d4c-e53e58a110db.png)
![Manrope_letter-m_1](https://user-images.githubusercontent.com/75579913/101287268-37d53b80-37bd-11eb-8ec8-b06400155727.png)
![Manrope_letter-m_3](https://user-images.githubusercontent.com/75579913/101287690-d06cbb00-37bf-11eb-8305-dd6b4a050f7f.png)

**Comment by sharanda** [comment]
@SJordd are you using Google Fonts version? Please use self-hosted font files from https://github.com/sharanda/manrope/ or https://manropefont.com/

**Comment by skalanter** [comment]
Hello,

I have this issue too: https://i.postimg.cc/G2VS8jcR/Capture.png
I used Google Fonts and also, I tried to upload fonts, locally, but it doesn't change.

But the issue persists yet.

Thanks
