### ISSUE TITLE
Slovak diacritics are a bit off

### ISSUE THREAD

**Issue by andrewshadura** [sharanda/manrope#63]
![Screenshot from 2020-12-15 13-47-19](https://user-images.githubusercontent.com/309253/102216892-1d494380-3edc-11eb-85f6-a4dbe046e3cd.png)

Unlike the French L-apostrophe combination, Ľ/ľ should not be wider than a normal L/l, same as Ť/ť. The width of the lowercase ť specifically here is okay, but the comma-resembling caron is probably a bit too high and a bit too big, whereas is could be a bit smaller than a normal comma/apostrophe.

**Comment by andrewshadura** [comment]
I must note the capitals look correct:
![Screenshot from 2020-12-15 13-51-11](https://user-images.githubusercontent.com/309253/102217275-a1033000-3edc-11eb-9892-5e9a3d759564.png)

**Comment by sharanda** [comment]
@andrewshadura thanks for reporting about this issue. It's fixed in v 4.505 (will publish soon).
