### ISSUE TITLE
Overlapping paths when using stroke outlines

### ISSUE THREAD

**Issue by rohanbhangui** [sharanda/manrope#64]
When using stroke outline option on text layers in apps such as illustrator and adobe XD, some letters have overlapping paths

**To Reproduce**
1. Create a text layer and type letters such ad 'd', 'P', 'R' or 'e' (there are other similar letters)
2. Use an outline stroke 
3. Paths overlap for these letters (see screenshots for additional letters)

**Expected behavior**
Glyphs should not overlap and be one contiguous shape 

**Screenshots**
https://imgur.com/a/gJViFQe
https://imgur.com/a/C0bvzq9

**Environment**
- OS: WIndows 10
- Apps: Adobe Illustrator and Adobe XD (possibly other apps)
- Latest version of font

**Comment by sharanda** [comment]
That's an expected look for a variable font. To avoid it, please use TTF/OTF font version from Github or manropefont.com, because those were exported with 'merge paths' option.
