### ISSUE TITLE
Manrope Not Working in Microsoft Powerpoint MAC

### ISSUE THREAD

**Issue by Tabstr** [sharanda/manrope#65]
<img width="893" alt="Screen Shot 2021-01-25 at 1 49 24 PM" src="https://user-images.githubusercontent.com/77995464/105767793-b8402f00-5f18-11eb-813e-79c597e06ef5.png">

Hi, I am having this issue with how Manrope is functioning in Microsoft Powerpoint on Mac. 
When installed (have tried both TTF and OTF) on a Mac and opened in Microsoft Powerpoint the Manrope font does not function properly. It opens in the dropdown menu and lists
Manrope >
Bold
Regular
Regular
Regular
Regular
Regular
Regular

When trying to select between them, the font doesn't change and it won't allow selecting between the font styles. This is odd because when installed and inspected in Mac's FontBook all of the styles are named and listed. I have attached a screenshot.

I have tried uninstalling and reinstalling the font, restarting Microsoft Powerpoint, installing OTF vs TTF, installing the variants vs. the static fonts. It all makes no difference in how it operates in Powerpoint on Mac. I have tested this on Powerpoint PC and it works well outside of Manrope Bold not being listed in the font options. 

This font will be used in a corporate PowerPoint template for a company with both Mac and PC users so having it function correctly in Powerpoint on both devices is key.

Please let me know if there is something that can be done to correct this issue or a solution I might be missing.

**Comment by sharanda** [comment]
Possibly related to this issue https://github.com/sharanda/manrope/issues/44
