### ISSUE TITLE
Font is converting (c) to copyright symbol

### ISSUE THREAD

**Issue by cgmonroe** [sharanda/manrope#67]
We have some legal docs that use (c) as a section id.  If we use the manrope font (woff2 from Google), this sequence gets converted to the copyright symbol.  If we use other fonts (e.g. just plain san serif) it shows correctly.   

Is there a way to disable / override this substitution?

**Comment by sharanda** [comment]
@cgmonroe sorry to hear that this feature turned into a bug 😄

You may either:
1. Turn OFF OpenType contextual alternatives feature with CSS: "font-feature-settings: "liga" 0;"
2. Use Cyrillic /с instead of Latin /c

**Comment by cgmonroe** [comment]
That works like a charm.  Thanks for the quick response and the great font.
