### ISSUE TITLE
Is their an alternative single-story "a" for this font?

### ISSUE THREAD

**Issue by dannydeserto** [sharanda/manrope#68]

**Comment by sharanda** [comment]
Let me try 😄

**Comment by sharanda** [comment]
@dannydeserto @tbrinton looks good actually
You can use it on the web like:
font-feature-settings: "ss01";
will publish soon
![Screenshot 2021-12-21 at 17 41 45](https://user-images.githubusercontent.com/32507483/146948323-c729b7df-be02-42b9-9e9d-1e18531442d9.png)
!

**Comment by tbrinton** [comment]
Awesome!! Thank you 🙏
