### ISSUE TITLE
Support for Greek

### ISSUE THREAD

**Issue by nicohaitas** [sharanda/manrope#7]
Very nice font I especially like the equal number spaces which is great for interfaces.

Is there a possibility for this font to also be available in Greek?

Thank you

**Comment by sharanda** [comment]
@nicohaitas Thanks. I received requests to add Greek characters before. Turned out Greek characters aren't that easy. I hope to learn more about it and add it around Summer 2019.

**Comment by nicohaitas** [comment]
Thanks for responding, looking forward to that inclusion.

**Comment by sharanda** [comment]
@nicohaitas hi, we began working on Manrope4. Just pushed first commit with Greek characters to the new branch: https://github.com/sharanda/manrope/tree/v4 (very early stage, needs adjustments and testing)

**Comment by nicohaitas** [comment]
Fantastic News! Please keep me informed on the progress
