### ISSUE TITLE
poor tracking between words in body sizes

### ISSUE THREAD

**Issue by aviaviaviii** [sharanda/manrope#70]
![image](https://user-images.githubusercontent.com/83166533/115991992-ea7d2d80-a5e8-11eb-9c70-9e6c00b40099.png)

the left one is manrope and right one is inter..
the spacing between the two words is so tight that it reduces the glanceability / readability of the overall typeface.
It works well for headlines and titles but not so much in body

![image](https://user-images.githubusercontent.com/83166533/115992036-2617f780-a5e9-11eb-812a-3e82ac93f3e9.png)
similarily here, the above is manrope and below is inter
inter is faster to read because of the distinction between the words.. 

I measured in pixels on the screen, if spacing between 2 words in inter is 13px; it's only 10px in manrope

please please fix, I want to use this as our default brand and company typeface but unable to do so :'(

**Comment by sharanda** [comment]
@aviaviaviii sorry, it seems quite subjective
