### ISSUE TITLE
Font weights not recognised on windows install properly

### ISSUE THREAD

**Issue by ljmdesign** [sharanda/manrope#72]
Fonts weights are recognised when viewed in the C: Windows -> Fonts directory however the weights are not identifying properly in applications ( e.g. Adobe XD ) and in the Windows settings menu, they are also not displaying correctly either. [Screen shot here showing font directory on left vs windows settings view on right](url)
![manrope-install-problems](https://user-images.githubusercontent.com/84547912/119061328-767f4b00-ba17-11eb-9a7e-9d0cfac214ae.PNG)

**Comment by ljmdesign** [comment]
Just saw the exsiting report for this one, the font files from github work fine, it's noteable that the google fonts have somehow defaulted back to the broken versions despite it being said they are fixed.

**Comment by sharanda** [comment]
Related to issue https://github.com/sharanda/manrope/issues/44
