### ISSUE TITLE
Consider type.today's Cyrillic review

### ISSUE THREAD

**Issue by thlinard** [sharanda/manrope#73]
https://type.today/en/journal/neo#Manrope

**Comment by sharanda** [comment]
That for reporting about it. Sadly, it was disappointing to see how they reviewed it. They haven’t tried to learn or see why I made it that way. Details they’ve mentioned I designed like that on purpose, and I actually like them. Sorry, can’t find anything useful from that review…

**Comment by thlinard** [comment]
> Thanks for reporting about it. Sadly, it was disappointing to see how they reviewed it. They haven’t tried to learn or see why I made it that way. Details they’ve mentioned I designed like that on purpose, and I actually like them.

Sorry that doesn't help you more.

> Sorry, can’t find anything useful from that review…

Perhaps the accent spacing problem in iї and її?

**Comment by fitojb** [comment]
Also, Ъъ. It really does look like a drawing mistake, the way these letters are in Manrope currently. It potentially affects legibility at small sizes.

**Comment by sharanda** [comment]
> Also, Ъъ. It really does look like a drawing mistake, the way these letters are in Manrope currently. It potentially affects legibility at small sizes.

Well, that’s how I wanted it to be. A little quirky, a little different. You may anytime modify the source file or just use another font
