### ISSUE TITLE
Display problems loading from Google Fonts

### ISSUE THREAD

**Issue by 0hwow** [sharanda/manrope#76]
Some letters are missing pixels loading from Google fonts in WP made site.
See "e" and "a":

![Screenshot 2021-08-24 at 16 32 09](https://user-images.githubusercontent.com/34716587/130635908-494dd06f-11eb-4259-9cb9-0570519cc4aa.png)

**Comment by alexmyczko** [comment]
i've seen that also with other google fonts, months ago, if not half a year. i'd suggest build it yourself and host it yourself:

https://github.com/alexmyczko/fnt (install from debian repo) if not available yet, for this specific font i've got builds here without problem in your screenshot:
https://sid.ethz.ch/debian/fonts-manrope/
