### ISSUE TITLE
Not supporting Modifier Letter Apostrophe (U+02BC)

### ISSUE THREAD

**Issue by ruslanmedia** [sharanda/manrope#80]
Not supporting (U+02BC) ʼ symbol. It's need for Uzbek language. Could you add this symbol too. Same with ’ (U+2019)

**Comment by sharanda** [comment]
@ruslanmedia Thanks for reaching out! Will add it in the next update

**Comment by sharanda** [comment]
Added in v 4.505 (will publish soon)
