### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by sharanda** [sharanda/manrope#82]
During the last minor update of the Manrope font, I've received a notification from Github that the build has failed.
@aaronbell @bghryct could you introduce how the build works or give an advice how to fix it?
Thanks!

**Comment by aaronbell** [comment]
Hi. Yes, so under the 'Actions' tab, the build are all listed and you can click on them to see the output of the build script. 

In this case, it appears that a glyph has become incompatible due to your recent update:

>fontmake.errors.FontmakeError: In 'Manrope.glyphs' -> 'master_ufo/Manrope.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'divide'

If you resolve that, it should continue without error.

**Comment by bghryct** [comment]
It's probably just a contour ordering problem.

**Comment by sharanda** [comment]
@bghryct @aaronbell thanks for the quick reply!
You mean, there must be something wrong with the divide character in the Glyphs source file?
Hm... Everything appears fine in Glyphs...

![Image 23 12 2021 at 00 18](https://user-images.githubusercontent.com/32507483/147156700-fd1bc5bc-1ea1-4c14-96ac-cdfb29b2fd56.jpg)

**Comment by bghryct** [comment]
Hmm. Maybe decompose. It's annoying but worth checking if it's something silly like that.

**Comment by aaronbell** [comment]
Is there a scaling transformation being applied to one of the components in one master but not in another master? Fontmake will decompose the master with the transformed component but not the other, leading to incompatibilities.

If so your two options are (1) decompose, or (2) apply a nominal transformation to the same component across every master. For example, a 99.99% scaling will solve the issue.

**Comment by sharanda** [comment]
@aaronbell @bghryct the build has succeeded! Thanks!
