### ISSUE TITLE
Gliph doesnt work

### ISSUE THREAD

**Issue by baaaarb** [sharanda/manrope#84]
Hi! I'm using Manrope as main font in the company I work at, but I noticed the "a" and "o" for ordinal numbers dont work properly (ordfeminine ª #00AA and ordmasculine º #00BA). They are shown as a normal "a" and "o". I'm using the otf and a portuguese keyboard, if this helps.

Anyone knows how to fix?

**Comment by sharanda** [comment]
@baaaarb this issue has already been fixed (https://github.com/sharanda/manrope/issues/52) please update the font files

**Comment by baaaarb** [comment]
Hey sharanda, thanks for your reply.
I tested on Adobe products and it's working well, but it's not working on Office for Windows..
