### ISSUE TITLE
Applying text stroke breaks the font

### ISSUE THREAD

**Issue by umm-wdc** [sharanda/manrope#96]
When we apply only text stoke the font breaks, please see screenshot below 
![image](https://user-images.githubusercontent.com/17593831/169655945-14acd165-ca36-48f3-b1e3-ec78f1cddb34.png)

**Comment by sharanda** [comment]
@umm-wdc this could happen if you use variable format or a version from Google fonts. To avoid such look, please use non-variable format from this repo or https://manropefont.com/ (non-variable formats were exported with 'remove overlap' option)
